let Swedish = true;

let swedenButton = document.getElementById("SwedenButton");
let ukButton = document.getElementById("UKButton");

function updateText() {

    if (Swedish) {
        document.getElementById("toptitle").textContent = "Etnicitet, Identitet & Neokolonialism i Born a Crime & Robinson Kruse";
        document.getElementById("title").textContent = "Välkommen till vår analys av Born a Crime av Trevor Noah, samt Robinson Kruse av Daniel Defoe";
        document.getElementById("text").textContent = "Born a Crime är en självbiografi av Trevor Noah om hans uppväxt i Sydafrika under apartheidens tid. Robinson Kruse är en robinsonad av Daniel Defoe som handlar om hans överlednad på en nästintill öde ö efter ett skeppsbrott. Båda böckerna är starkt fokuserade på teman som etnicitet, identitet och neokolonialism, vår websida kommer presentera hur dessa teman förekommer i båda böckerna samt hur det ser ut idag.";
        document.getElementById("block1Title").textContent = "Historisk Kontext och Författare";
        document.getElementById("block1Text").textContent = "Trevor Noah är en författare och komiker, känd för sin bok Born a Crime (publicerad 15 november 2016) där han delar med sin bild på hans uppväxt i apartheidens tid tillsammans med sin mamma bokens budskap är att bevisa hur stor påverkan identitet och etnicitet kan betyda i samhället. Daniel Defoe däremot är en engelsk författare, känd för sin bok Robinson Kruse (1719), som handlar om en man som överlever på en öde ö efter ett skeppsbrott. Boken är den första robinsonaden och har blivit en klassiker inom ämnet. Defoe utforskar teman som överlevnad och människans kamp mot naturen, samt hur människans identitet, etnicitet och moral kan påverka deras överlevnad och liv på ön.";
        document.getElementById("block2title").textContent = "Analys";
        document.getElementById("block2text").textContent = "I Born a Crime av Trevor Noah presenteras temat identitet och etnicitet genom Trevors uppväxt under Apartheid i Sydafrika. Trevor är barn till en svart mamma och en vit pappa, vilket var olagligt under apartheid. Därför känner han ofta att han inte riktigt hör hemma i någon grupp. Ett exempel är när han skriver “I was born a crime.” Det visar hur raslagarna påverkade människors identitet och liv. Trevor Noahs budskap är att ras och identitet ofta bestäms av samhällets regler, inte av vem man egentligen är. I Robinson Crusoe av Daniel Defoe presenteras temat identitet och etnicitet genom huvudpersonens liv på ön och hans relation till mannen han räddar, som han kallar Friday. Crusoe tar kontroll över ön och lär Friday engelska och kristendom, vilket visar hur europeisk kultur framställs som överlägsen. Ett exempel är när Crusoe ger honom namnet “Friday”, vilket visar att han bestämmer över hans identitet och roll. Detta speglar idéer kopplade till Colonialism. Författarens perspektiv visar hur många européer under den tiden såg sin egen kultur och makt som naturlig och självklar. Båda böckerna visar hur samhället fördelar makt, ojämnlikhet mellan olika grupper.";
        document.getElementById("block3title").textContent = "Upplysningen";
        document.getElementById("block3text").textContent = "Upplysningen var en kulturhistorisk rörelse under 1700-talet. Upplysningen betonade förnuft, vetenskap och individuell frihet, vilket påverkade framför allt Daniel Defoes liv och verk. Defoe (1660–1731) var journalist, affärsman och författare, och trodde på praktisk kunskap, hårt arbete och människans möjlighet att förbättra sitt liv. Hans mest kända roman, Robinson Crusoe, handlar om en man som skapar ett nytt liv på en öde ö med hjälp av sitt förnuft och sitt arbete, vilket speglar upplysningens idéer om att lösa problem och forma sin egen framtid. Både Born a Crime och Robinson Crusoe visar hur individer använder förnuft, erfarenhet och handling för att överleva och skapa sin identitet, vilket är centrala idéer i Upplysningstiden.";
        document.getElementById("block4title").textContent = "Koppling till det Moderna Samhället och vår Åsikt";
        document.getElementById("block4text").textContent = "Robinson Kruse skrevs under upplysningen när människan började tro på sin egen förmåga att överkomma naturen genom förnuft och teknik. Samtidigt präglades tiden av kolonialism, där de vita såg sig själv som överlägsen i jämförelse med andra kulturer (vilket syns i Robinsons relation till Fredag). Born a Crime utspelar sig under och efter apartheid i Sydafrika. Det är ett mer modernt sammanhang fast med mer fokus på rasism och kampen för grundläggande mänskliga rättigheter. I dagens samhälle är rasism fortfarande alldeles för vanligt, kolonialismen lever kvar i form av ekonomi där företag eller stater fortfarande utnyttjar andra länder eller grupper. Båda böckerna visar att det är viktigt att förstå historien och hur den påverkar oss idag, så att vi kan arbeta för en mer rättvis och jämlik framtid.";
        document.getElementById("block5title").textContent = "Tack för oss!"
    } 
    else {
        document.getElementById("toptitle").textContent = "Ethnicity, Identity & Neocolonialism in Born a Crime & Robinson Crusoe";
        document.getElementById("title").textContent = "Welcome to our analysis of Born a Crime by Trevor Noah, as well as Robinson Kruse by Daniel Defoe";
        document.getElementById("text").textContent = "Born a Crime is a memoir by Trevor Noah about his childhood in South Africa during the time of apartheid. Robinson Crusoe is a robinsonade by Daniel Defoe that tells the story of his survival on a nearly deserted island after a shipwreck. Both books are heavily focused on themes such as ethnicity, identity and neocolonialism, our website will present how these themes are present in both books as well as how it looks today.";
        document.getElementById("block1Title").textContent = "Historical Context and Authors";
        document.getElementById("block1Text").textContent = "Trevor Noah is an author and comedian, known for his book Born a Crime (published November 15, 2016), in which he shares his perspective on growing up during the apartheid era alongside his mother. The book's message is to demonstrate the profound impact that identity and ethnicity can have on society. Daniel Defoe, on the other hand, is an English author known for his book Robinson Crusoe (1719), which tells the story of a man who survives on a deserted island after a shipwreck. The book is the first robinsonade and has become a classic within the genre. Defoe explores themes such as survival and the human struggle against nature, as well as how a person's identity, ethnicity, and morals can influence their survival and life on the island.";
        document.getElementById("block2title").textContent = "Analysis";
        document.getElementById("block2text").textContent = "In Born a Crime by Trevor Noah, the theme of identity and ethnicity is presented through Trevor’s childhood during Apartheid in South Africa. Trevor is the child of a Black mother and a white father, which was illegal during apartheid. Because of this, he often feels that he does not fully belong to any group. One example is when he writes, “I was born a crime.” This shows how racial laws affected people’s identities and lives. Trevor Noah’s message is that race and identity are often determined by society’s rules, not by who someone truly is. In Robinson Crusoe by Daniel Defoe, the theme of identity and ethnicity is presented through the main character’s life on the island and his relationship with the man he rescues, whom he calls Friday. Crusoe takes control of the island and teaches Friday English and Christianity, which shows how European culture is portrayed as superior. One example is when Crusoe gives him the name “Friday,” which shows that he decides his identity and role. This reflects ideas connected to Colonialism. The author’s perspective shows how many Europeans at that time saw their own culture and power as natural and unquestioned. Both books show how society distributes power and creates inequality between different groups.";
        document.getElementById("block3title").textContent = "The Enlightenment";
        document.getElementById("block3text").textContent = "The Enlightenment was a cultural-historical movement during the 18th century. It emphasized reason, science, and individual freedom, which notably influenced the life and work of Daniel Defoe. Defoe (1660–1731) was a journalist, businessman, and author who believed in practical knowledge, hard work, and the human potential to improve one's life. His most famous novel, Robinson Crusoe, tells the story of a man who creates a new life on a deserted island through the use of reason and labor, reflecting Enlightenment ideas about problem-solving and shaping one's own future. Both Born a Crime and Robinson Crusoe demonstrate how individuals use reason, experience, and action to survive and forge their identity, which are central ideas of the Enlightenment era.";
        document.getElementById("block4title").textContent = "Connection to Modern Society and our Opinion";
        document.getElementById("block4text").textContent = "Robinson Crusoe was written during the Enlightenment when people began to believe in their own ability to overcome nature through reason and technology. At the same time, the era was marked by colonialism, where white people saw themselves as superior compared to other cultures (which is evident in Crusoe's relationship with Friday). Born a Crime takes place during and after apartheid in South Africa. It is a more modern context but with a greater focus on racism and the struggle for basic human rights. In today's society, racism is still far too common, and colonialism persists in the form of economics where companies or states still exploit other countries or groups. Both books show that it is important to understand history and how it affects us today, so that we can work towards a more just and equal future.";
        document.getElementById("block5title").textContent = "That's all from us, thank you!"
    }
}

swedenButton.onclick = function() {
    Swedish = true;
    updateText();
};

ukButton.onclick = function() {
    Swedish = false;
    updateText();
};